// Generated by CoffeeScript 1.9.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root["eval"] = function() {
    var equation;
    equation = $(".equation").val();
    return calculate(equation);
  };

  root.calculate = function(equation) {
    var answer, i, index, len, number, numbers, symbol;
    symbol = equation.split((0 - 9) + alert(symbol));
    numbers = equation.split('+' | '-' | '*' | '/' | '(' | ')');
    for (index = i = 0, len = numbers.length; i < len; index = ++i) {
      number = numbers[index];
      numbers[index] = number.replace(/^\s+|\s+$/g, "");
      numbers[index] = +numbers[index];
    }
    numbers.unshift(symbol);
    answer = root.operator_map(numbers);
    return answer;
  };

  root.operator_map = function(equation_array) {
    var finalnum, i, len, num, op;
    op = equation_array.shift();
    finalnum = equation_array.shift();
    for (i = 0, len = equation_array.length; i < len; i++) {
      num = equation_array[i];
      finalnum = root.string_math(op, finalnum, num);
    }
    return finalnum;
  };

  root.string_math = function(op, num1, num2) {
    if (op === '+') {
      return num1 + num2;
    } else if (op === '-') {
      return num1 - num2;
    }
  };

}).call(this);
